baseurl = "https://blog.whatthedude.com/"
languageCode = "en-us"
title = "What The Blog?"
theme = "hugo-natrium-theme"
rssLimit = 20
paginate = 20
pygmentsCodefences = true
pygmentsStyle = "native"

[taxonomies]
    category = "categories"
    tag = "tags"

[permalinks]
    post = "/:slug/"
    page = "/:slug/"

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = -110

[[menu.main]]
    name = "Tags"
    url = "/tags"
    weight = -120

# [[menu.main]]
#     name = "Categories"
#     url = "/categories"
#     weight = -130

[params]
    description = ""

    [params.logo]
    url = "logo.png"
    width = 50
    height = 50
    alt = "Logo"